spring:
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: kafka.demo.consumer
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring:
        json:
          trusted:
            packages: 'com.ramy.kafkademo.*'

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

demo:
  async-executor:
    core-pool-size: 50
    max-pool-size: 50
    queue-capacity: 1000
    thread-name-prefix: KafkaListener-
