server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    driver-class-name : org.postgresql.Driver
    username : postgres
    password : 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
