spring :
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/platform
    driver-class-name : org.postgresql.Driver
    username : root
    password : 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: WARN

server:
  port: 8081