server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/test?autoReconnect=true&characterEncoding=UTF-8&serverTimeZone=UTC"
    username: "root"
    password: "1234"
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-shoppingmall
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

file:
  directory: C:\Users\User\Desktop\TIL\Tech\Spring+Kotlin+Vue\backend\src\images