spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name : org.mariadb.jdbc.Driver
    username : root
    password : 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace
      SQL: WARN
